/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.1 Update 1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2017 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Millis_TMR.h"
#include "Clock_1.h"
#include "Millis_ISR.h"
#include "USB_UART.h"
#include "USB_UART_SPI_UART.h"
#include "USB_UART_PINS.h"
#include "USB_UART_SPI_UART_PVT.h"
#include "USB_UART_PVT.h"
#include "USB_UART_BOOT.h"
#include "UART.h"
#include "UART_SPI_UART.h"
#include "UART_PINS.h"
#include "UART_SPI_UART_PVT.h"
#include "UART_PVT.h"
#include "UART_BOOT.h"
#include "nRF24_DEFS.h"
#include "nRF24_FUNCS.h"
#include "nRF24_HAL.h"
#include "nRF24_COMMANDS.h"
#include "nRF24_CONFIG.h"
#include "CE.h"
#include "CE_aliases.h"
#include "SS.h"
#include "SS_aliases.h"
#include "LED.h"
#include "LED_aliases.h"
#include "SPI.h"
#include "SPI_SPI_UART.h"
#include "SPI_PINS.h"
#include "SPI_SPI_UART_PVT.h"
#include "SPI_PVT.h"
#include "SPI_BOOT.h"
#include "MASTER_UNIT.h"
#include "MASTER_UNIT_aliases.h"
#include "NRF_ISR.h"
#include "NRF_ISR_aliases.h"
#include "UART_IN.h"
#include "UART_IN_aliases.h"
#include "UART_OUT.h"
#include "UART_OUT_aliases.h"
#include "USB_UART_SCBCLK.h"
#include "USB_UART_tx.h"
#include "USB_UART_tx_aliases.h"
#include "USB_UART_SCB_IRQ.h"
#include "USB_UART_rx.h"
#include "USB_UART_rx_aliases.h"
#include "UART_SCBCLK.h"
#include "UART_SCB_IRQ.h"
#include "SPI_SCBCLK.h"
#include "SPI_sclk_m.h"
#include "SPI_sclk_m_aliases.h"
#include "SPI_miso_m.h"
#include "SPI_miso_m_aliases.h"
#include "SPI_mosi_m.h"
#include "SPI_mosi_m_aliases.h"
#include "SPI_SCB_IRQ.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyDMA.h"
#include "CyLFClk.h"

/*[]*/

