class Holding_Registers:
	Winch_ID, \
	DIP_Switch_Status, \
	Soft_Reset, \
	Max_Velocity, \
	Max_Acceleration, \
	Encoder_Radius, \
	Target_Setpoint, \
	Target_Setpoint_Offset, \
	Kp_velocity, \
	Ki_velocity, \
	Kd_velocity, \
	Max_Encoder_Feedrate, \
	Kp_position, \
	Ki_position, \
	Kd_position, \
	Kp, \
	Ki, \
	Kd, \
	PID_Setpoint, \
	Target_X, \
	Target_Y, \
	Target_Z, \
	Target_X_Offset, \
	Target_Y_Offset, \
	Target_Z_Offset, \
	Field_Length, \
	Field_Width, \
	Current_Encoder_Count, \
	Current_PWM, \
	Current_RPM, \
	Homing_Flag, \
	Homing_switch, \
	Current_X, \
	Current_Y, \
	Current_Z, \
	Current_Length_Winch0, \
	Current_Length_Winch1, \
	Current_Length_Winch2, \
	Current_Length_Winch3, \
	Target_Length_Winch0, \
	Target_Length_Winch1, \
	Target_Length_Winch2, \
	Target_Length_Winch3, \
	Current_Force_Winch0, \
	Current_Force_Winch1, \
	Current_Force_Winch2, \
	Current_Force_Winch3, \
	ADC0, \
	ADC1, \
	ADC2, \
	ADC3, \
	Follow_Waypoints, \
	Current_Waypoints_Pointer, \
	Number_of_Waypoints, \
	Dwell_Time, \
	load_cell_neg, \
	load_cell_H, \
	load_cell_L, \
	load_cell_zero, \
	load_cell_cal, \
	load_cell_error, \
	mcp266_error, \
	underrun_error, \
	underload_error, \
	overload_error, \
	tether_reached_target, \
	minimum_duty_cycle, \
	minimum_tension, \
	maximum_tension, \
	kinematics_test_X, \
	kinematics_test_Y, \
	kinematics_test_Z, \
	kinematics_test_U, \
	kinematics_test_M, \
	kinematics_test_N, \
	kinematics_test_A, \
	kinematics_test_B, \
	kinematics_test_C, \
	kinematics_test_D, \
	X1, \
	Y1, \
	Z1, \
	X2, \
	Y2, \
	Z2 = range(85)

Map = Holding_Registers